# Generated by Django 5.1.5 on 2025-02-24 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('reservada', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='mesa',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='comida.mesa'),
            preserve_default=False,
        ),
    ]
