# Generated by Django 5.1.5 on 2025-02-18 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0002_mensajecontacto_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajecontacto',
            name='usuario',
        ),
    ]
