# Generated by Django 5.1.5 on 2025-02-19 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0004_otromodelo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OtroModelo',
            new_name='MiModeloPersonalizado',
        ),
    ]
