# Generated by Django 5.1.5 on 2025-02-19 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0005_rename_otromodelo_mimodelopersonalizado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MiModeloPersonalizado',
            new_name='OtroModelo',
        ),
    ]
