# Generated by Django 5.1.5 on 2025-02-27 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0006_producto_carrito_itemcarrito_carrito_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrito',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='itemcarrito',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='ItemCarrito',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
