# Generated by Django 5.1.5 on 2025-02-19 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0006_rename_mimodelopersonalizado_otromodelo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
        migrations.DeleteModel(
            name='OtroModelo',
        ),
    ]
