# Generated by Django 5.1.5 on 2025-02-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0007_remove_itemcarrito_carrito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredientes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
