# Generated by Django 5.1.5 on 2025-02-19 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0007_remove_customuser_bio_delete_otromodelo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
