# Generated by Django 5.1.5 on 2025-03-01 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0008_product_ingredientes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='ingredientes',
        ),
        migrations.AddField(
            model_name='product',
            name='ingredientes',
            field=models.ManyToManyField(related_name='productos', to='comida.ingrediente'),
        ),
    ]
