# Generated by Django 5.1.5 on 2025-03-01 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0009_ingrediente_remove_product_ingredientes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ingredientes',
        ),
        migrations.DeleteModel(
            name='Ingrediente',
        ),
    ]
