# Generated by Django 5.1.5 on 2025-03-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0010_remove_product_ingredientes_delete_ingrediente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('personalizable', 'Personalizable'), ('sabores', 'Con Sabores'), ('simple', 'Simple'), ('bebida', 'Bebida')], max_length=20)),
                ('ingredientes', models.ManyToManyField(blank=True, related_name='productos', to='comida.ingrediente')),
                ('sabores', models.ManyToManyField(blank=True, related_name='productos', to='comida.sabor')),
            ],
        ),
    ]
