# Generated by Django 5.1.5 on 2025-03-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0011_ingrediente_sabor_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sabores',
            field=models.ManyToManyField(blank=True, to='comida.sabor'),
        ),
    ]
