# Generated by Django 5.1.5 on 2025-03-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0012_alter_producto_imagen_alter_producto_sabores'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_descripcion',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default=1, upload_to='productos'),
            preserve_default=False,
        ),
    ]
