# Generated by Django 5.1.5 on 2025-03-03 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0013_producto_imagen_descripcion_alter_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen_descripcion',
        ),
    ]
