# Generated by Django 5.1.5 on 2025-03-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0014_remove_producto_imagen_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_descripcion',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
