# Generated by Django 5.1.5 on 2025-03-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0016_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='comprobante',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/'),
        ),
    ]
