# Generated by Django 5.1.5 on 2025-03-05 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0017_alter_pedido_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
