# Generated by Django 5.1.5 on 2025-03-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0018_pedido_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
