# Generated by Django 5.1.5 on 2025-03-05 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0019_alter_product_precio'),
    ]

    operations = [
    ]
