# Generated by Django 5.1.5 on 2025-03-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0020_auto_20250305_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='metodo_entrega',
            field=models.CharField(choices=[('domicilio', 'Domicilio'), ('recoger', 'Recoger en local')], default='recoger', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
