# Generated by Django 5.1.5 on 2025-03-05 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0021_pedido_metodo_entrega_alter_producto_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='metodo_entrega',
        ),
    ]
