# Generated by Django 5.1.5 on 2025-03-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0024_alter_pedido_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_profile.png', null=True, upload_to='profile_pics/'),
        ),
    ]
