# Generated by Django 5.1.5 on 2025-03-12 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0030_pedido_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='usuario',
        ),
    ]
