# Generated by Django 5.1.5 on 2025-03-12 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0033_reserva_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=50),
        ),
    ]
