# Generated by Django 5.1.5 on 2025-03-12 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0034_reserva_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='usuario',
        ),
    ]
