# Generated by Django 5.1.5 on 2025-03-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0035_remove_pedido_estado_remove_reserva_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('en_proceso', 'En Proceso')], default='pendiente', max_length=20),
        ),
    ]
