# Generated by Django 5.1.5 on 2025-03-13 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0040_pedido_usuario_pedido_visible_para_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='visible_para_usuario',
        ),
    ]
