# Generated by Django 5.1.5 on 2025-03-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0045_reserva_estado_reserva_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='productos',
            field=models.JSONField(default=list),
        ),
    ]
