# Generated by Django 5.1.5 on 2025-03-14 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0047_alter_pedido_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='productos',
            field=models.JSONField(default=list),
        ),
    ]
