# Generated by Django 5.1.5 on 2025-03-16 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0049_alter_pedido_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('nequi', 'Nequi'), ('daviplata', 'Daviplata'), ('contra_entrega', 'Contra Entrega')], max_length=50),
        ),
    ]
