# Generated by Django 5.1.5 on 2025-03-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0051_pedido_usuario_reserva_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmado', 'Confirmado'), ('Enviado', 'Enviado'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmado', 'Confirmado'), ('Cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
